server:
    port: 8081
spring:
# mysql://bb68b2ec90ccd3:09e8de7e@us-cdbr-east-06.cleardb.net/heroku_ad30dd59e74b08c?reconnect=true
    datasource:
        url: jdbc:mysql://localhost:3306/oop
        # url: jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_ad30dd59e74b08c?reconnect=true
        username: root
        # username: bb68b2ec90ccd3
        password: root
        # password: 09e8de7e
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            # dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB
    config:
        import: application-mail.yml
rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
springdoc:
    swagger-ui:
        path: /

